package videoController

object VgaConstants {
  val H_ACTIVE_VIDEO = 200
  val H_FRONT_PORCH = 10
  val H_SYNC_PULSE = 32
  val H_BACK_PORCH = 22
  val H_TOTAL = H_ACTIVE_VIDEO + H_FRONT_PORCH + H_SYNC_PULSE + H_BACK_PORCH
  val V_ACTIVE_VIDEO = 600
  val V_FRONT_PORCH = 1
  val V_SYNC_PULSE = 4
  val V_BACK_PORCH = 23
  val V_TOTAL = V_ACTIVE_VIDEO + V_FRONT_PORCH + V_SYNC_PULSE + V_BACK_PORCH
}
